language: python
sudo: false

python:
  - "3.5"
  - "3.6"

install:
  - pip install pip -U
  - pip install -r requirements.txt
  - pip install -r {{cookiecutter.project_slug}}/requirements.in

script:
  - ./runtests.sh
